# Generated by Django 6.0.3 on 2026-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=500, verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(default='', max_length=100, verbose_name='Delivery Area/Neighborhood'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Delivery Phone'),
        ),
    ]
