# Generated by Django 6.0.3 on 2026-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_image_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='change_reason',
            field=models.CharField(blank=True, choices=[('initial', 'Initial Price'), ('promotion', 'Promotion'), ('discount', 'Discount'), ('price_adjustment', 'Price Adjustment'), ('market_change', 'Market Change'), ('sales_event', 'Sales Event'), ('other', 'Other')], max_length=255),
        ),
    ]
